/*
 * Action Types
 * -----------
 */
export const LOAD_FIELDS = 'LOAD_FIELDS';
export const LOAD_FIELDS_SUCCESS = 'LOAD_FIELDS_SUCCESS';
export const LOAD_FIELDS_FAILURE = 'LOAD_FIELDS_FAILURE';

export const LOAD_CONTENT = 'LOAD_CONTENT';
export const LOAD_CONTENT_SUCCESS = 'LOAD_CONTENT_SUCCESS';
export const LOAD_CONTENT_FAILURE = 'LOAD_CONTENT_FAILURE';
